### ISSUE TITLE
Build issue with pod

### ISSUE THREAD

**Issue by shashiLBB** [imgix/imgix-swift#10] opened 2017-10-11 07:12 UTC
I am using both Objective C and Swift languages in my project and have created a bridging header. My project had been working from a year but upon installing Imgix pod it's giving me build error. 

Error: In an objective c file -> projectName-Swift.h file not found.
Can you please help me?

**Comment by shashiLBB** [comment] 2017-10-11 07:15
I installed imgix pod 0.1.4 version, I am using XCode 9, swift 3.2. Upon installing it gave me the error in ImgixClient.Swift and String+ImgixSwift.Swift. I had to manually change the code.

**Comment by sherwinski** [comment] 2020-02-12 21:40
I'm going to close this issue as it is quite old. If for whatever reason this is still an issue, feel free to comment or reopen.

**Closed as completed by sherwinski** 2020-02-12 21:40 UTC

**Comment by chenthorne** [comment] 2020-03-10 18:25
@sherwinski we are seeing this in our project still. We have to go in and manually remove a line that's added each time we do a new pod install.

The line:
```
SWIFT_OBJC_INTERFACE_HEADER_NAME = ImgixSwift.h
```

It's added to each Pod configuration file

Edit:
Most likely caused by https://github.com/imgix/imgix-swift/blob/ae489f1d7ed297b11526e4b422262f01059047f4/ImgixSwift.podspec#L12

**Comment by sherwinski** [comment] 2020-03-10 18:35
Hi @chenthorne
I think you are correct, that line should have been removed in the latest release. Just for my information, would you mind telling me what version of imgix-swift you're currently on?

**Comment by chenthorne** [comment] 2020-03-10 20:17
Thanks for the quick reply. We are using 1.1.0.

**Comment by sherwinski** [comment] 2020-03-10 20:21
Great, I'll have a patch out shortly. Thanks for bringing this to our attention.

**Comment by sherwinski** [comment] 2020-03-13 18:12
Hi @chenthorne, the issue you mentioned should be fixed in [v1.1.1](https://github.com/imgix/imgix-swift/releases/tag/1.1.1)

**Comment by chenthorne** [comment] 2020-03-17 20:51
Great, thanks!
